### ISSUE TITLE
Cannot execute stats page

### ISSUE THREAD

**Issue by ShahBinoy** [youngsterxyf/redis-sentinel-manager#12]
Hi I am trying to use your UI but. Date picker not working, getting error
'Uncaught TypeError: $(...).datetimepicker is not a function'

line number 28099 in main.js
$(function () {
    $('#begin_datetime').datetimepicker({
        format: 'YYYY-MM-DD HH:mm:ss',
        defaultDate: new Date(Date.now() - (60 \* 60 \* 12 \* 1000)),
        sideBySide: true
    });

**Comment by kitelife** [comment]
@ShahBinoy Have you executed `npm install` ?

**Comment by ShahBinoy** [comment]
Yes I followed the steps in your README
My current versions are
[root@host]# node -v
v5.9.1
[root@host]# pm2 -v
1.0.2
[root@host]# npm -v
3.7.3

![screenshot from 2016-04-01 11 08 30](https://cloud.githubusercontent.com/assets/5808900/14211079/2cdeb5ec-f7fa-11e5-8583-7adec2a6ea38.png)

**Comment by kitelife** [comment]
@ShahBinoy I'm sorry. I have found the reason of the bug - `cn-bootstrap-datetimepicker` package requires jquery ">=1.8.3 <2.2.0". I have updated the `package.json`, see:  commit [#f679efb](https://github.com/youngsterxyf/redis-sentinel-ui/commit/f679efbb955869296a2205e05ee5c5909a0f270e) , you can pull it and try it again. Thanks!

**Comment by ShahBinoy** [comment]
Yes that fixed it.

Thank you
